[project]
name = "libnetconf2"
make_archive_script = "distro/scripts/make-archive.sh"

[upstream]
archive_url = "https://github.com/CESNET/libnetconf2/archive/v{{ version }}/libnetconf2-{{ version }}.tar.gz"
version_script = "distro/scripts/upstream-version.sh"

[apkg]
compat = 2
